apiVersion: v1
kind: Service
metadata:
  name: eks-demo-service
spec:
  type: LoadBalancer        # AWS creates ELB automatically!
  selector:
    app: eks-demo
  ports:
    - port: 80
      targetPort: 80
