apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path    # ← add this line
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/k8s-data
