apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path    # k3s default storage class
  resources:
    requests:
      storage: 1Gi
