apiVersion: v1
kind: Service
metadata:
  name: hpa-demo-service
  namespace: dev
spec:
  selector:
    app: hpa-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
