name: K8s CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: cicd-demo
  EKS_CLUSTER: dev-cluster
  NAMESPACE: dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY ./Day-7/k8s-cicd/app

      # Tag Image
      - name: Tag Docker Image
        run: |
          ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}

          docker tag $ECR_REPOSITORY:latest $ECR_URI:latest
          docker tag $ECR_REPOSITORY:latest $ECR_URI:${{ github.sha }}

          echo "ECR_URI=$ECR_URI" >> $GITHUB_ENV

      # Push Image
      - name: Push Docker Image
        run: |
          docker push $ECR_URI:latest
          docker push $ECR_URI:${{ github.sha }}

      # Update kubeconfig
      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --name ${{ env.EKS_CLUSTER }} \
            --region ${{ env.AWS_REGION }}

      # Create Namespace if not exists
      - name: Create Namespace
        run: |
          kubectl create namespace ${{ env.NAMESPACE }} \
            --dry-run=client -o yaml | kubectl apply -f -

      # Deploy Kubernetes Manifests
      - name: Deploy Application
        run: |
          kubectl apply -f k8s/deployment.yaml -n ${{ env.NAMESPACE }}
          kubectl apply -f k8s/service.yaml -n ${{ env.NAMESPACE }}

      # Update Deployment Image
      - name: Update Deployment Image
        run: |
          kubectl set image deployment/cicd-demo \
          cicd-demo=$ECR_URI:${{ github.sha }} \
          -n ${{ env.NAMESPACE }}

      # Wait for Rollout
      - name: Wait for Rollout
        run: |
          kubectl rollout status deployment/cicd-demo \
          -n ${{ env.NAMESPACE }} \
          --timeout=180s

      # Show Service
      - name: Get Service
        run: |
          kubectl get svc -n ${{ env.NAMESPACE }}
